name: econ_data
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - openpyxl
  - pyreadstat
  - pip:
    - pymer4
    - streamlit
    - plotly
    - altair>=5.0
    - vl-convert-python
